# Generated by Django 2.0.3 on 2019-10-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isPriceless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('smallPrice', models.DecimalField(decimal_places=2, default=9.99, max_digits=3)),
                ('largePrice', models.DecimalField(decimal_places=2, default=9.99, max_digits=3)),
                ('smallOnly', models.BooleanField(default=False)),
                ('fromMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='orders.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('large', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(to='orders.Pizza'),
        ),
    ]
