# Generated by Django 2.0.3 on 2019-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='largePrice',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=4),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='smallPrice',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
