# Generated by Django 2.0.3 on 2019-10-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuoption_largeonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='smallAndLarge',
            field=models.BooleanField(default=True),
        ),
    ]
