# Generated by Django 2.0.3 on 2019-10-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191024_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='name',
            field=models.CharField(default='placeholder', max_length=50),
            preserve_default=False,
        ),
    ]
