# Generated by Django 2.0.3 on 2019-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_mainitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='toppings',
            field=models.ManyToManyField(related_name='toppings', to='orders.Topping'),
        ),
    ]
