# Generated by Django 2.2.6 on 2019-10-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191024_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='toppingLimit',
            field=models.IntegerField(default=4),
        ),
    ]
