# Generated by Django 2.2.6 on 2019-10-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_mainitem_toppinglimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
