# Generated by Django 2.2.6 on 2019-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191027_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='delivered',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
