# Generated by Django 2.2.6 on 2019-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191027_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='toppingLimit',
            field=models.IntegerField(default=4),
        ),
    ]
